### ISSUE TITLE
Remove/reduce blank lines in the "about" tab

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#10]
To avoid having a vertical scrollbar in the GUI.

**Comment by lcalisto** [comment]
Is it still happening in the latest version? if so, can you please send a print screen? I cannot reproduce in my computer.

**Comment by gioman** [comment]
> Is it still happening in the latest version?

@lcalisto yep

![Screenshot_20191129_121444](https://user-images.githubusercontent.com/1951107/69868540-e2a94480-12a1-11ea-899e-f9c6ca5d5b75.png)

I guess that blank lines can be removed before and after "reference...", after "co-funded" (maybe in this case is a matter of trimming the logo) and after "plugin developed by..."

**Comment by lcalisto** [comment]
Can you please have a look?
