### ISSUE TITLE
Do not allow geographic CRSs

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#14]
Only allow projected CRSs.

**Comment by lcalisto** [comment]
This issue should be fixed. The ok button is disabled in case of geographic CRS and a message is raised. But more testing is needed. Can you please test it @gioman ?

**Comment by gioman** [comment]
@lcalisto Same consideration as for https://github.com/NaturalGIS/mapping_ecosystem_services/issues/15 

In this case for some reason the warning shows 3 times.

**Comment by lcalisto** [comment]
Sorry, "mea culpa".

**Comment by lcalisto** [comment]
Can you test again?

**Comment by gioman** [comment]
@lcalisto almost :) The ok button is disabled (great!) and the warning shows once when selecting/changing one of the input layers, but it also pop up when 

selecting the output folder
adding a class to the "source" list
adding a class to the "target" list

**Comment by lcalisto** [comment]
I had the idea that this was the expected behavior, in order to remind why ok button was disabled. Anyway, now the warning should only appears when selecting study area or landuse. Please check if this is ok
