### ISSUE TITLE
Check if study area layer and land use one have the same CRS

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#15]
Block the "ok" otherwise (and raise a message?).

**Comment by lcalisto** [comment]
This issue should be fixed but further testing is needed. Can you please test @gioman?

**Comment by gioman** [comment]
It works, but I ask if this can be improved.

The warning message shows up two times (it should only 1), as I guess it is checked if land use has the same CRS as study area and also vice versa.

Moreover the user can close the warnings but the "ok" button (if all inputs are chosen) remain/become active, while it should remain/become disabled. 

it is difficult stuff?

**Comment by lcalisto** [comment]
Sorry, "Mea culpa"! I'll fix it asap.

**Comment by gioman** [comment]
> Sorry, "Mea culpa"! I'll fix it asap.

no worries!

**Comment by lcalisto** [comment]
Can you test again?

**Comment by gioman** [comment]
@lcalisto almost :) The ok button is disabled (great!) and the warning shows once when selecting/changing one of the input layers, but it also pop up when 

selecting the output folder
adding a class to the "source" list
adding a class to the "target" list

**Comment by lcalisto** [comment]
I had the idea that this was the expected behavior, in order to remind why ok button was disabled. Anyway, now the warning only appears when selecting study area or landuse. Please check if this is ok.
