### ISSUE TITLE
change some words/strings in the GUI

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#2]
max distance (CRS units) -> analysis distance (CRS units)
study area -> study area/s
land use -> land use areas (must be in the same CRS of study area/s layer)
land use field name -> land use classification attribute
not linear??? -> Gaussian
output raster pixel size (CRS units) -> output raster spatial resolution (CRS units)
origin -> land use classes
target -> "target" land use classes
source -> "source" land use classes and values

**Comment by lcalisto** [comment]
It's done. Needs confirmation.
