### ISSUE TITLE
It was transmitted the wrong formula for the "gaussian" computation (VERY SORRY)

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#21]
Correct:
computed_value=source_value*((2,72^(((computed_distance/analysis_distance)*(computed_distance/analysis_distance)*-4)+0,92))/SQRT(6,3))

Wrong:
computed_value=source_value*((2.72^((((computed_distance/analysis_distance) * ((computed_distance/analysis_distance) * -4) + 0.92))/sqrt(6.3))

Sorry for the parentheses in the wrong place...

**Comment by gioman** [comment]
Note both linear and gaussian formulas round results to 3 decimal places.

**Comment by lcalisto** [comment]
Sorry, aren't you missing a *? Can you please confirm if it's like this:

computed_value=source_value*((2,72^(((computed_distance/analysis_distance)*(computed_distance/analysis_distance)-4)+0,92))/SQRT(6,3))

**Comment by gioman** [comment]
@lcalisto Use the formula as above. Will check a bit later if it misses the "*".

**Comment by gioman** [comment]
@lcalisto you were right

10*((2,72^(((computed_distance/analysis_distance)*(computed_distance/analysis_distance)*-4)+0,92))/SQRT(6,3))

**Comment by gioman** [comment]
@lcalisto wait GH is removing "*" from the formula when I save the comment...

**Comment by gioman** [comment]
`=10*((2,72^(((computed_distance/analysis_distance)*(computed_distance/analysis_distance)*-4)+0,92))/SQRT(6,3))`

**Comment by lcalisto** [comment]
😆
Is it 
```
10*((2,72^(((computed_distance/analysis_distance)*(computed_distance/analysis_distance)*-4)+0,92))/SQRT(6,3))
```

or 

```
source_value*((2,72^(((computed_distance/analysis_distance)*(computed_distance/analysis_distance)-4)+0,92))/SQRT(6,3))
```

I implemented the last one can you check?

**Comment by gioman** [comment]
> Is it

`source_value*((2,72^(((computed_distance/analysis_distance)*(computed_distance/analysis_distance)*-4)+0,92))/SQRT(6,3))`

**Comment by lcalisto** [comment]
yes

**Comment by gioman** [comment]
`source_value*((2,72^(((computed_distance/analysis_distance)*(computed_distance/analysis_distance)*-4)+0,92))/SQRT(6,3))`

> yes

yes, the correct forumula is the one above here.

**Comment by lcalisto** [comment]
ok, should be correct then. Can you recheck?

**Comment by gioman** [comment]
test blocked by https://github.com/NaturalGIS/mapping_ecosystem_services/issues/8#issuecomment-560007027
