### ISSUE TITLE
Add "centroids"/"boundaries" and "linear"/"gaussian" to the name of the output GPKG/Tiff

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#28]
Subject says it all.

**Comment by lcalisto** [comment]
Done. Please check. I kept "computed" and "output_result" in tif and gpkg naming please check if you want to replace/remove this words.

**Comment by gioman** [comment]
Test blocked by https://github.com/NaturalGIS/mapping_ecosystem_services/issues/8#issuecomment-560007027

**Comment by lcalisto** [comment]
Can you check?

**Comment by gioman** [comment]
Fixed.
