### ISSUE TITLE
add a readme

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#3]
subject says it all.

**Comment by gioman** [comment]
See: https://github.com/NaturalGIS/mapping_ecosystem_services/pull/24

**Comment by lcalisto** [comment]
Perhaps we need to update it with the latest gui: centroids and borders distance analysis.

**Comment by gioman** [comment]
> Perhaps we need to update it with the latest gui: centroids and borders distance analysis.

updated.
