### ISSUE TITLE
add a plugin icon

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#4]
attached

![plugin_icon](https://user-images.githubusercontent.com/1951107/69322949-b48e8980-0c3d-11ea-83dd-9a0f18c5e9cb.png)

**Comment by lcalisto** [comment]
It's done. Needs confirmation.

**Comment by gioman** [comment]
@lcalisto I was not able to make it show in the plugin menu entry/toolbar. Possibly it is needed to build some file?

![icon](https://user-images.githubusercontent.com/1951107/69797276-53c7f980-11c7-11ea-99d3-584cb96fddc2.png)

**Comment by gioman** [comment]
Also I think that the icon filename must be "icon.png"(?) -> https://github.com/NaturalGIS/mapping_ecosystem_services/blob/master/metadata.txt#L31

**Comment by lcalisto** [comment]
Yes filename must be `icon.png` and we need to build it with `pb_tool compile`

**Comment by gioman** [comment]
See: https://github.com/NaturalGIS/mapping_ecosystem_services/pull/23
