### ISSUE TITLE
Add analysis/SQL using centroids

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#6]
This needs also a combo box in the GUI.

**Comment by lcalisto** [comment]
Added as default because it's much faster. Please check if it's working as expected!

**Comment by gioman** [comment]
@lcalisto as discussed, the formula implementation is ok, but this analysis has a flaw because of a case that wasn't taken into account by who requested the plugin:

there can be two parcels (one source and one target) with distance between centroids that is > to the analysis distance but the distance between the boundaries is less than the analysis distance. In fact if the parcels are big enough you can have adjacent ones with the distance between centroids that is > to the analysis distance.

The proposed solution is the following (please evaluate how difficult is):

1) do the full distance analysis using the centroids
2) all the results where the distance is < to the analysis distance are copied to the results table
3) for the cases where the distance between centroids is > to the analysis distance to a buffer of the source geometry (buffer distance is the analysis distance) and do test if it intersects the target geometry, if result is TRUE then copy this record to the results table

**Comment by gioman** [comment]
>     3. for the cases where the distance between centroids is > to the analysis distance to a buffer of the source geometry (buffer distance is the analysis distance) and do test if it intersects the target geometry, if result is TRUE then copy this record to the results table

@lcalisto 
given that the analysis done with the centroids is anyway an approximation, the above test/check can be done comparing the BBOXes of the buffer of the source parcels and the target parcels. This should help speed up the computations.

**Comment by gioman** [comment]
@lcalisto I'm think this could be easily "solved" if instead of centroids the analysis could be done computing just the min distance between the bboxes of geometries (which is basically as fast as using centroids) but is more accurate than using just centroids. I'm checking with the client.

**Comment by gioman** [comment]
> I'm checking with the client.

@lcalisto confirmed, we can use parcels BBOXEs (ST_Envelope ?) instead of centroids. This "solves" the issue in a very simple way.

**Comment by gioman** [comment]
> confirmed, we can use parcels BBOXEs (ST_Envelope ?) instead of centroids. This "solves" the issue in a very simple way.

@lcalisto let's call this strategy (in the GUI) "bounding boxes", I guess this triggers also a change in the output file name.

**Comment by lcalisto** [comment]
I just checked and it is indeed faster. dont forget that the lines visually might be strange because they are  between the bboxes and not the real parcels. Can we then delete the centroids from the gui and replace them by the bounding boxes?

**Comment by gioman** [comment]
> I just checked and it is indeed faster. dont forget that the lines visually might be strange because they are between the bboxes and not the real parcels

yes, but it still a better approximation than centroids, without the problem of the centroids (i.e. two adjacent parcels can have centroids distance > distance analysis, while the BBOXEs of two adjacent parcels are almost certainly intersecting each other, so ST_Distance will return 0).



>  Can we then delete the centroids from the gui and replace them by the bounding boxes?

yes "remove" the centroids strategy and replace it with the BBOX one, in theory it is only needed to replace ST_Centroid with ST_Envelope.

**Comment by lcalisto** [comment]
Done. can you please test? I decided to save both bboxes in raw table just for debug purposes. Please let me know if you still want to keep them or if I can remove them from raw table.

**Comment by gioman** [comment]
>  decided to save both bboxes in raw table just for debug purposes. Please let me know if you still want to keep them or if I can remove them from raw table.

@lcalisto keep them! :)
